# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrap_quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('file_path', models.ImageField(height_field=models.PositiveSmallIntegerField(), upload_to='%Y/%m/%d/', width_field=models.PositiveSmallIntegerField())),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='deliver_boat',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='scrap_where_located',
        ),
        migrations.AddField(
            model_name='quote',
            name='all_inclusive_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='all_inclusive_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='scrap_only_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='scrap_only_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quoteimages',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_images', to='scrap_quote.Quote'),
        ),
        migrations.AddField(
            model_name='quoteimages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
