# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0002_auto_20180404_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='hull_material',
            field=models.CharField(choices=[(None, 'Please select the material the hull is made from'), ('Aluminium', 'Aluminium'), ('Carbon Fibre', 'Carbon Fibre'), ('Ferro Cement', 'Ferro Cement'), ('GRP / Fibreglass', 'GRP / Fibreglass'), ('Plastic', 'Plastic'), ('Steel', 'Steel'), ('Wood', 'Wood')], max_length=20),
        ),
    ]
