# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0003_auto_20180404_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
