# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0004_auto_20180405_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='scrap_at_location',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't Know", "Don't Know")], max_length=10),
        ),
    ]
