# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0005_quote_scrap_at_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardousMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_type', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
