# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0006_hazardousmaterials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='hazardous_mats',
        ),
        migrations.AddField(
            model_name='quote',
            name='hazardous_mats',
            field=models.ManyToManyField(to='scrap_quote.HazardousMaterials'),
        ),
    ]
