# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0007_auto_20180408_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='keel_type',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('Fin Keel', 'Fin Keel'), ('Bilge Keel', 'Bilge Keel'), ('Other', 'Other')], max_length=10),
        ),
    ]
