# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0008_auto_20180408_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatInWaterOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_water', models.CharField(max_length=40)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Boat in Water Option',
                'verbose_name_plural': 'Boat in Water Options',
            },
        ),
        migrations.CreateModel(
            name='EngineTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=20)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Engine Type',
                'verbose_name_plural': 'Engine Types',
            },
        ),
        migrations.CreateModel(
            name='HullMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hull_material', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Hull Material',
                'verbose_name_plural': 'Hull Materials',
            },
        ),
        migrations.CreateModel(
            name='ScrapAtLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_at_location', models.CharField(max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Scrap At Location Option',
                'verbose_name_plural': 'Scrap At Location Options',
            },
        ),
        migrations.CreateModel(
            name='TrailerOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_option', models.CharField(max_length=40)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trailer Option',
                'verbose_name_plural': 'Trailer Options',
            },
        ),
        migrations.CreateModel(
            name='TypeOfBoat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_boat', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Type of Boat',
                'verbose_name_plural': 'Type of Boat',
            },
        ),
        migrations.CreateModel(
            name='TypeOfKeel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_keel', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Type of Keel',
                'verbose_name_plural': 'Type of Keel',
            },
        ),
        migrations.AlterModelOptions(
            name='hazardousmaterials',
            options={'verbose_name': 'Hazardous Material', 'verbose_name_plural': 'Hazardous Materials'},
        ),
        migrations.RemoveField(
            model_name='quote',
            name='engine_removed',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='trailer_road_legal',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='type_of_engine',
        ),
        migrations.AddField(
            model_name='hazardousmaterials',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='boat_in_water',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrap_quote.BoatInWaterOptions'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='has_trailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrap_quote.TrailerOptions'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='hull_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrap_quote.HullMaterials'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='keel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrap_quote.TypeOfKeel'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='scrap_at_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrap_quote.ScrapAtLocation'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='type_of_boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrap_quote.TypeOfBoat'),
        ),
        migrations.AddField(
            model_name='quote',
            name='engine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='scrap_quote.EngineTypes'),
            preserve_default=False,
        ),
    ]
