# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0009_auto_20180408_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginetypes',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
