# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0010_enginetypes_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineStillRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_still_run', models.CharField(max_length=50)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Engine Still Run Option',
                'verbose_name_plural': 'Engine Still Run Options',
            },
        ),
        migrations.AlterField(
            model_name='scrapatlocation',
            name='scrap_at_location',
            field=models.CharField(max_length=30),
        ),
    ]
