# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0011_auto_20180408_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='engine_still_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrap_quote.EngineStillRun'),
        ),
    ]
