# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0013_auto_20180408_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='boat_location',
            field=models.CharField(default='PO12 2UN', max_length=20),
            preserve_default=False,
        ),
    ]
