# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0014_quote_boat_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteimages',
            name='height',
        ),
        migrations.RemoveField(
            model_name='quoteimages',
            name='width',
        ),
        migrations.AlterField(
            model_name='quoteimages',
            name='file_path',
            field=models.ImageField(upload_to='%Y/%m/%d/'),
        ),
    ]
