# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0018_auto_20180414_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='hazardous_mats',
            field=models.ManyToManyField(blank=True, null=True, to='scrap_quote.HazardousMaterials'),
        ),
    ]
