# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0021_auto_20180414_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.AlterModelOptions(
            name='quotelogstatus',
            options={'verbose_name': 'Quote Log Status Code', 'verbose_name_plural': 'Quote Log Status Codes'},
        ),
        migrations.AlterField(
            model_name='quotelog',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_log', to='scrap_quote.QuoteLogStatus'),
        ),
    ]
