# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0023_quotelog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotelog',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_logs', to='scrap_quote.Quote'),
        ),
        migrations.AlterField(
            model_name='quotelog',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_logs', to='scrap_quote.QuoteLogStatus'),
        ),
        migrations.AlterField(
            model_name='quotelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
