# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0025_auto_20180414_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelog',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', protocol='IPv4'),
            preserve_default=False,
        ),
    ]
