# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import scrap_quote.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_quote', '0026_quotelog_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteimages',
            name='file_path',
            field=models.ImageField(upload_to=scrap_quote.models.user_upload_path),
        ),
    ]
