# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrap_quote', '0028_quote_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', tinymce.models.HTMLField()),
                ('is_read', models.BooleanField(default=False)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_messages', to='scrap_quote.Quote')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
