# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_auto_20180329_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
